<?php
//Includes
include('includes/admin.inc');

/**
 * Impliments hook_menu
 */
function BootstrapBlocks_module_menu() {
  $items = array();
  $items['admin/appearance/bootstrapblocks'] = array(
    'title' => t('Bootstrap Blocks'),
    'access arguments' => array('administer themes'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('BootstrapBlocks_settings_form'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/appearance/bootstrapblocks/settings'] = array(
    'title' => 'Main',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10 
  );

  return $items;
}
